Log when maxMessageSize is exceeded
vlingo/vlingo-http pull request #66
Opened 2020-11-02 17:10 UTC by Florian-Schoenherr

This logs as an error if maxMessageSize is exceeded.

- Should I [change this](https://github.com/vlingo/vlingo-http/blob/f9e4e6141e6d29d6dd771ea6bd8b953d59d5a22b/src/test/java/io/vlingo/http/resource/StaticFilesResourceTest.java#L41), now that I'm using a much smaller max-size?
- The same code is [used here](https://github.com/vlingo/vlingo-http/blob/f9e4e6141e6d29d6dd771ea6bd8b953d59d5a22b/src/main/java/io/vlingo/http/resource/ServerActor.java#L529), can we make this DRY easily somehow?
- At the point where I'm logging, only `response` is available. The `request` is obviously used in some methods, but I'm not quite sure how I get it over to this method. I would like to log which resource is too big (response only holds Body, sadly no filename).

2020-11-02 21:41 UTC, VaughnVernon requested changes
@Florian-Schoenherr The `try-catch` is in the wrong place. Please close this PR.

The try-catch should go around this line of code, which is where failure is occurring inside.

https://github.com/vlingo/vlingo-http/blob/9bff5f60e27777a81390b12ad275ad9c13cf1610/src/main/java/io/vlingo/http/resource/ServerActor.java#L444

You can see it in the stacktrace here:

![vlingo-http-server-actor-buffer-overflow](https://user-images.githubusercontent.com/2637036/97922190-4d1bfd80-1d19-11eb-8fb4-116d9bd616c1.png)

I have made the change and pushed it into master. Please use it to debug.

2020-11-02 21:41 UTC, VaughnVernon commented on src/main/java/io/vlingo/http/resource/ServerActor.java
> +      } catch (IllegalStateException e) {
@Florian-Schoenherr Suggestion: use `Exception` rather than specific `IllegalStateException` to make sure you catch every possible failure.

2020-11-02 22:03 UTC, Florian-Schoenherr commented
This PR wasn't about the Exception you're mentioning, but the fact that when you configure a `maxMessageSize` of e.g. 4096 you still get files served which are larger than that, without any notice, via
`BasicConsumerByteBuffer.allocate(0, size);`

2020-11-03 02:17 UTC, VaughnVernon commented
@Florian-Schoenherr You are trying to catch an exception but there is none to catch, other than OOME or some other unrecoverable exception. I don't know why you think there should be some sort of notification ("without any notice") when this happens . This does exactly what it was designed to do; that is, if the pooled buffers are too small then allocate a non-pooled buffer that is large enough. It's GC'd after its use.

2020-11-03 09:07 UTC, Florian-Schoenherr commented
I didn't get that it should use a non-pooled buffer. Also, I did misunderstand some of our conversation on Slack, but now I get it.
Should I say something about that in the docs? Because I misunderstood to a large extend because it seems so definitive, it's called **max**MessageSize. That's also why I wanted to log. Now I know this should not be an Exception ([and yes, there is one to catch, which I'm throwing myself, because I thought that size>maxSize is illegal state](https://github.com/vlingo/vlingo-http/blob/f9e4e6141e6d29d6dd771ea6bd8b953d59d5a22b/src/main/java/io/vlingo/http/resource/ServerActor.java#L459)).
If you don't want any logging, we can close.
Else I would make one more commit, where you just have:

```
if (size < maxMessageSize) {
  return responseBufferPool.acquire("ServerActor#BasicCompletedBasedResponseCompletes#bufferFor");
}
logger().debug("Response exceeds maxMessageSize " + maxMessageSize + ", allocating size " + size + " instead.")
return BasicConsumerByteBuffer.allocate(0, size + 1024);
```

2020-11-03 16:37 UTC, VaughnVernon commented
@Florian-Schoenherr I think time zones played in. We don't want to log this permanently because this is a very hot section of code. Even with `debug()` level it can be costly because the message must still be sent and it generates garbage to be collected.

I have added a richer explanation in the docs. Thanks for the suggestion. Please see if this clarifies things.

https://docs.vlingo.io/vlingo-http#file-based-configuration

2020-11-03 17:58 UTC, closed without merging